# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
# %run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np 

#### 2. Print the numpy version and the configuration (★☆☆)

In [6]:
print(np.__version__)
print(np.__config__)

1.21.4
<module 'numpy.__config__' from 'C:\\Users\\patel\\ML_PATH\\env\\lib\\site-packages\\numpy\\__config__.py'>


#### 3. Create a null vector of size 10 (★☆☆)

In [16]:
a = np.empty(10)

#### 4. How to find the memory size of any array (★☆☆)

In [17]:
np.size(a)

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [18]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [31]:
np.put(a, 4, 1, mode='clip')
print(a)

[4.67296746e-307 1.69121096e-306 1.78019082e-306 1.89146896e-307
 1.00000000e+000 1.00000000e+000 1.24610723e-306 1.29061142e-306
 1.11263624e-307 1.06806669e-306]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [40]:
vec = np.arange(10, 50)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [42]:
vec_rev = vec[::-1]
print(vec_rev)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [44]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [99]:
a = [1, 2, 0, 0, 4, 0]
print(np.argwhere(np.array(a) == 0))


[[2]
 [3]
 [5]]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [58]:
eye_ = np.eye(3)
print(eye_)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [63]:
print(np.random.random((3,3,3)))

[[[0.41737277 0.91472413 0.51897926]
  [0.08437987 0.91433457 0.4452596 ]
  [0.92250386 0.42206118 0.84297279]]

 [[0.38337163 0.68864487 0.04110035]
  [0.59979447 0.03157572 0.5598655 ]
  [0.3170375  0.09289086 0.74363766]]

 [[0.54409493 0.81707978 0.74348221]
  [0.09092615 0.51336755 0.72149251]
  [0.65762632 0.13101688 0.60147399]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [64]:
b = np.random.random((10, 10))
max_b = b.max()
min_b = b.min()
print(max_b, min_b)

0.9957372109361248 0.005079020088233244


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [65]:
rand = np.random.random(30)
print(np.mean(rand))

0.5041771852784483


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [69]:
a = np.zeros((5,5))
a[:,[0,-1]] = 1
a[[0, -1], :] = 1
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [111]:
arr = np.random.random((6,6))
arr[0:, [0,-1]] = 0 
arr[[0,-1],0:] = 0
print(arr)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.87746874 0.4434557  0.53726877 0.10047602 0.        ]
 [0.         0.4750522  0.23724588 0.725033   0.22287717 0.        ]
 [0.         0.84632414 0.34114074 0.21622667 0.55510201 0.        ]
 [0.         0.03438252 0.40547575 0.67379046 0.52017314 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [83]:
print( 0 * np.nan)       # np.nan
print( np.nan == np.nan) # False
print( np.inf > np.nan)  # False
print(np.nan- np.nan)    # np.nan
print(np.nan in set([np.nan])) # True 
print(0.3 == 3* 0.1) # False

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [85]:
print(np.diag((1,2,3,4), -1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [95]:
a = np.array(['*']*64).reshape(8,8)
a[0::2, 1::2] = 0
a[1::2, 0::2] = ' '
print(a)

[['*' '0' '*' '0' '*' '0' '*' '0']
 [' ' '*' ' ' '*' ' ' '*' ' ' '*']
 ['*' '0' '*' '0' '*' '0' '*' '0']
 [' ' '*' ' ' '*' ' ' '*' ' ' '*']
 ['*' '0' '*' '0' '*' '0' '*' '0']
 [' ' '*' ' ' '*' ' ' '*' ' ' '*']
 ['*' '0' '*' '0' '*' '0' '*' '0']
 [' ' '*' ' ' '*' ' ' '*' ' ' '*']]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [112]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [119]:
print(np.tile(np.array([['*', '0'], ['0', '*']]), [4, 4]))


[['*' '0' '*' '0' '*' '0' '*' '0']
 ['0' '*' '0' '*' '0' '*' '0' '*']
 ['*' '0' '*' '0' '*' '0' '*' '0']
 ['0' '*' '0' '*' '0' '*' '0' '*']
 ['*' '0' '*' '0' '*' '0' '*' '0']
 ['0' '*' '0' '*' '0' '*' '0' '*']
 ['*' '0' '*' '0' '*' '0' '*' '0']
 ['0' '*' '0' '*' '0' '*' '0' '*']]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [129]:
a = np.random.seed(10)
arr_a = np.random.random((5,5))
a_max, a_min = arr_a.max(), arr_a.min()
arr_norm = (arr_a - arr_a.min())/(a_max - a_min)
print(arr_norm)

[[0.80823251 0.01769843 0.66322948 0.7845168  0.52089242]
 [0.23260785 0.20445058 0.79686805 0.17395695 0.08888513]
 [0.71769454 1.         0.         0.53530637 0.85173194]
 [0.64098263 0.75602799 0.30325904 0.96248417 0.74846616]
 [0.56727463 0.14558165 0.38906147 0.70587058 0.46120088]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [130]:
##??

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [134]:
a, b = np.zeros((5,3)), np.ones((3,2))
c = a.dot(b)
print(c)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [152]:
arr = np.arange(1, 11)

print(np.where((arr>2) & (arr<9), arr*-1, arr))

[ 1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [165]:
#print(sum(range(5), -1)) # 9 
from numpy import * 
print(sum(range(5), -1)) # 9 

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [171]:
z =89
print(z<z>z)

False


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [179]:
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

0
[-2.14748365e+09]


C:\Users\patel\AppData\Local\Temp/ipykernel_6272/550553992.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [190]:
arr = np.arange(18, 37, 0.5, dtype='float')


#### 30. How to find common values between two arrays? (★☆☆)

In [197]:
arr1 = np.array([2,3,4,5,5,6])
arr2 = np.array([2,3,4,5,3,5])

print(np.intersect1d(arr1, arr2))

[2 3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
#####   DONT RUNNNNNNNN  -----___np.seterr(all="ignore")___-----

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [198]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


C:\Users\patel\AppData\Local\Temp/ipykernel_6272/2770867030.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [206]:
print(np.datetime64('today', 'D')) # today 
print(np.datetime64('today', 'D') - np.timedelta64('1','D'))

2021-12-27
2021-12-26


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [208]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [214]:
A = np.array([2,3,4,5])
B = np.array([4,8,9,10])
np.add(A, B, out = B)
np.divide(A, 2, out = A)
np.negative(A, out = A)
np.multiply(A, B, out = A)

UFuncTypeError: Cannot cast ufunc 'true_divide' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [230]:
print(np.tile(np.arange(5, dtype='float'), [5,1]))

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [236]:
def generate():
    for i in range(10):
        yield i 

Y = np.fromiter(generate(), dtype='float')
print(Y)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [238]:
np.linspace(0,1, num=10, endpoint=False)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [240]:
rand_vec = np.random.random(10)
rand_vec.sort()
rand_vec

array([0.04689632, 0.11398436, 0.19894754, 0.30070006, 0.35165264,
       0.54758616, 0.62628715, 0.819287  , 0.82868133, 0.8568503 ])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [251]:
z = np.arange(10)
print(np.add.reduce(z))

45


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [255]:
a = np.random.randint(2, 8, 4)
b = np.random.randint(2, 8, 5)

print(np.array_equal(a,b))  

False


#### 43. Make an array immutable (read-only) (★★☆)

In [258]:
x = np.arange(3)
x.flags.writeable = False
x[1] = 9

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)